version: '3'

services:

  service_balance:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./ServiceDriver
    volumes:
      - ./ServiceDriver/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '3050:80'
    networks:
      - frontend
      - backend
    links:
      - static_front
      - api_route

  static_front:
    build:
      dockerfile: Dockerfile
      context: ./FrontEnd/nginx
    volumes:
      - ./FrontEnd/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./FrontEnd:/code
    networks:
      - frontend
    links:
      - dynamic_front

  dynamic_front:
    build:
      dockerfile: Dockerfile
      context: ./FrontEnd
    volumes:
      - ./FrontEnd:/code
    networks:
      - frontend

  api_route:
    build:
      dockerfile: Dockerfile
      context: ./api/nginx
    volumes:
      - ./api/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/code
    networks:
      - backend
    links:
      - api

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api:/code
    networks:
      - backend
      - database
    links:
      - db

  db:
    build:
      dockerfile: Dockerfile
      context: ./DB
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: testcase
      MYSQL_USER: FinalBot
      MYSQL_PASSWORD: Trym3B30nc3
    volumes:
      - ./SampleDat:/var/lib/mysql
      - ./DB:/scripts
    networks:
      - database

volumes:
  SampleDat:
    driver: local
  db:
    driver: local

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
  database:
    driver: "bridge"
