apiVersion: v1
kind: Service
metadata:
  name: static-api-service
  labels:
    tier: backend
spec:
  selector:
    app: static-api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-api-deployment
  labels:
    app: static-api
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-api
  template:
    metadata:
      labels:
        app: static-api
        tier: backend
    spec:
      containers:
        - name: projectpath-static-api-prod
          image: interaze/projectpath-api-route-prod:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000