FROM mysql:8.0

RUN echo "mysql -u root -ptestcase -e \"GRANT ALL PRIVILEGES ON Final_Project.* TO 'FinalBot'@'%';\"\nmysql -u root -ptestcase -e \"FLUSH PRIVILEGES\";" >> /usr/local/bin/docker-entrypoint.sh